import Head from 'next/head'
import Image from 'next/image'
import Link from "next/link"
import styles from '../styles/Home.module.css'
import contacts from "./api/contacts"
import Layout from '../components/Layout'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
         <Link href="/learn/next">
          <a className={styles.card}>
              <h2>Documentation via Component Next &rarr;</h2>
              <p>Learn about Next.js in an interactive course with quizzes!</p>
            </a>
         </Link>


         <Link href="/learn/react">
          <a className={styles.card}>
              <h2>Documentation via Component React &rarr;</h2>
              <p>Learn about Next.js in an interactive course with quizzes!</p>
            </a>
         </Link>

         <Link href="/learn/angular">
          <a className={styles.card}>
              <h2>Documentation via Dynamic Component Angular &rarr;</h2>
              <p>Learn about Angular in an interactive course with quizzes!</p>
            </a>
         </Link>

         <Link href="/learn/vue">
          <a className={styles.card}>
              <h2>Documentation via Dynamic Component Vue &rarr;</h2>
              <p>Learn about VueJS in an interactive course with quizzes!</p>
            </a>
         </Link>
        </div>
        
        <div className={styles.grid}>
          {contacts.map(c => <><Link href={`/contacts/${c.id}`}><a className={styles.card}>{c.id} </a></Link></>)}
        </div>
        <div className={styles.grid}>
          {contacts.map(c => <Layout key="{c.id">{c.id}</Layout>)}
        </div>
        <div className={styles.grid}>
          <Link href={`/products`}><a className={styles.card}>Products</a></Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
